# Security audit configuration for cargo-audit
# This file documents known security issues that have been assessed and accepted

[advisories]
# List RUSTSEC IDs that should be ignored with justification
# Example:
# ignore = [
#     "RUSTSEC-2020-0001", # Example: Known issue in dev dependency, not exploitable in our use case
# ]
ignore = []

# Warn about informational advisories
informational_warnings = ["unmaintained", "notice"]

# Severity threshold for exiting with error
# Options: "info", "low", "medium", "high", "critical"
severity_threshold = "high"