name: Fuzz Testing
on:
  schedule:
    # Run fuzz tests daily
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  fuzz:
    name: ci:fuzz
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        target: [blueprint_parser, selector, stack_plan_validation]
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      
      - uses: dtolnay/rust-toolchain@7b1c307e0dcbda6122208f10795a713336a9b35a # nightly
        with:
          toolchain: nightly
      
      - uses: Swatinem/rust-cache@82a92a6e8fbeee089604da2575dc567ae9ddeaab # v2.7.5
        with:
          workspaces: ". -> target fuzz -> fuzz/target"
      
      - name: Install cargo-fuzz
        run: cargo install cargo-fuzz
      
      - name: Run fuzz test - ${{ matrix.target }}
        run: |
          cd fuzz
          cargo +nightly fuzz run ${{ matrix.target }} -- -max_total_time=300